# Generated by Django 4.2.7 on 2023-11-18 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='nivel_riesgo',
            field=models.CharField(choices=[('moderado', 'Moderado'), ('intermedio', 'Intermedio'), ('severo', 'Severo')], max_length=50),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='sexo',
            field=models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino')], max_length=10),
        ),
    ]
