# Generated by Django 4.2.7 on 2023-11-05 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del doctor', max_length=100)),
                ('rut', models.CharField(help_text='RUT del doctor', max_length=15)),
                ('telefono', models.CharField(help_text='Teléfono de contacto del doctor', max_length=15)),
                ('correo', models.EmailField(help_text='Correo electrónico del doctor', max_length=254)),
                ('especialidad', models.CharField(help_text='Especialidad del doctor', max_length=100)),
                ('turno', models.BooleanField(default=False, help_text='¿Está en turno?')),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctores',
            },
        ),
    ]
